services:
  app:
    container_name: pure-admin-services
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: production  # 使用多阶段构建的目标阶段
    ports:
      - "${APP_PORT:-3000}:3000"
    env_file: .env.production.local
    depends_on:
      - postgres
      - redis
    command: sh -c "npm run migrate:deploy && npm run prisma:seed:deploy && node /usr/src/app/dist/main.js"

  postgres:
    container_name: pure-admin-postgres
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pure_postgres_data:/var/lib/postgresql/data

  redis:
    container_name: pure-admin-redis
    image: redis:6
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - pure_redis_data:/data

volumes:
  pure_postgres_data:
  pure_redis_data:
