version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development  # 使用多阶段构建的目标阶段
    ports:
      - "${PORT:-3001}:3001"
    env_file: .env.test
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "pnpm migrate:dev && pnpm prisma:seed && pnpm run start:dev"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      MINIO_ROOT_USER: wansongtao
      MINIO_ROOT_PASSWORD: w.12345.st
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  redis_data:
  minio_data: