services:
  minio:
    image: bitnami/minio:latest
    container_name: pure-admin-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: wansongtao
      MINIO_ROOT_PASSWORD: w.12345.st
      MINIO_DEFAULT_BUCKETS: avatar
    command: /opt/bitnami/scripts/minio/run.sh --console-address ":9001"
    restart: unless-stopped

volumes:
  minio_data:
